### ISSUE TITLE
Ready for production?

### ISSUE THREAD

**Issue by betterbydesign** [jameswestnz/serverpilot-api-php#3]
I am looking to use Server pilot and have whmcs, is this still in development? How does it get installed and function?

**Comment by jameswestnz** [comment]
@Satori83, I'm using this in a few production apps, and does what I need it to... But it does need further development to bring inline with updates to the API, and I will likely do these as/when needed at my end. More than happy to fix/add things on request :)

I'm in the process of getting it composer ready, but for now you can download and include Client.php and follow the instructions in the readme.
